# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-17 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svn_path', models.CharField(max_length=255, verbose_name='svn地址')),
                ('principal', models.CharField(max_length=255, verbose_name='负责人')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('tag_date', models.DateField(verbose_name='tag日期')),
                ('tag_version', models.CharField(max_length=255, verbose_name='tag版本')),
                ('desc', models.TextField(max_length=255, verbose_name='版本简要说明')),
                ('bug_fix', models.CharField(blank=True, max_length=255, null=True, verbose_name='修改的缺陷')),
                ('update_function', models.CharField(blank=True, max_length=255, null=True, verbose_name='新增功能')),
                ('solve_problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='已解决的问题')),
                ('exist_risk', models.CharField(blank=True, max_length=255, null=True, verbose_name='已存在的风险')),
                ('roll_back', models.CharField(max_length=255, verbose_name='出现问题回滚措施')),
                ('is_monitored', models.CharField(max_length=255, verbose_name='新上线功能是否可监控')),
                ('develop_person', models.CharField(max_length=255, verbose_name='版本开发人员')),
                ('monitored_person', models.CharField(max_length=255, verbose_name='升级后监控人员')),
                ('verify_person', models.CharField(max_length=255, verbose_name='升级后功能验证人员')),
                ('need_test', models.CharField(max_length=255, null=True, verbose_name='是否需要测试')),
                ('is_test_pass', models.CharField(default='no', max_length=255, null=True, verbose_name='是否测试通过')),
                ('is_examine_pass', models.CharField(default='no', max_length=255, null=True, verbose_name='是否审核通过')),
                ('handle_person', models.CharField(max_length=255, null=True, verbose_name='升级操作人员')),
                ('is_backspace', models.CharField(default='no', max_length=255, null=True, verbose_name='是否被回退')),
                ('deploy_type', models.CharField(default='common upgrade', max_length=255, null=True, verbose_name='升级类型')),
                ('create_time', models.DateField(auto_now=True, verbose_name='工单创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_module_name', to='cmdb.ProjectModule', verbose_name='项目名称')),
                ('update_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_project', to='cmdb.ProjectModule', verbose_name='更新项目')),
            ],
            options={
                'verbose_name': '升级任务',
                'verbose_name_plural': '升级任务',
                'permissions': (('scan_deploytask', 'Can scan deploytask info'), ('examine_deploytask', 'Can examine deploytask'), ('backspace_deploytask', 'Can backspace deploytask')),
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=255, verbose_name='脚本名称')),
                ('script_type', models.CharField(max_length=255, verbose_name='脚本类型')),
                ('script_content', models.TextField(verbose_name='脚本内容')),
                ('script_dir', models.CharField(max_length=255, verbose_name='脚本路径')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
                'permissions': (('scan_script', 'Can scan script info'), ('execute_script', 'Can execute script'), ('transfer_script', 'Can transfer script')),
            },
        ),
    ]
