# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_billing_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='billing sql文件')),
                ('sql_pay_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='pay sql 文件')),
                ('jar_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='jar 文件')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '文件上传执行',
                'verbose_name_plural': '文件上传执行',
            },
        ),
    ]
