# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-20 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0002_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传文件用户'),
        ),
    ]
