# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-20 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_uploadfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
