# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-21 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20180820_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'permissions': (('execute_file', 'Can execute file'),), 'verbose_name': '文件上传执行', 'verbose_name_plural': '文件上传执行'},
        ),
    ]
