# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_auto_20180821_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploytask',
            name='update_project',
        ),
        migrations.AlterField(
            model_name='deploytask',
            name='update_date',
            field=models.DateField(auto_now_add=True, verbose_name='更新日期'),
        ),
    ]
