# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_auto_20180827_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='upgrade_step',
            field=models.TextField(blank=True, null=True, verbose_name='升级步骤'),
        ),
    ]
