# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_deploytask_upgrade_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='email_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='需要接受邮件的人'),
        ),
    ]
