# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-06 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_deploytask_is_sql_exec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploytask',
            name='update_date',
        ),
    ]
