# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0014_auto_20180914_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='is_upgrade_success',
            field=models.CharField(default='no', max_length=255, verbose_name='是否升级成功'),
        ),
    ]
