# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0015_deploytask_is_upgrade_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploytask',
            name='is_upgrade',
            field=models.CharField(default='no', max_length=255, verbose_name='是否已升级'),
        ),
    ]
