# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-29 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0018_auto_20180926_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='is_upgrade_failure',
            field=models.CharField(default='no', max_length=255, verbose_name='是否升级失败'),
        ),
        migrations.AddField(
            model_name='deploytask',
            name='upgrade_failure_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='升级失败时间'),
        ),
    ]
