# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0019_auto_20180929_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='is_upgrade_partition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='是否需要先升级部分节点'),
        ),
    ]
