# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-29 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0020_deploytask_is_upgrade_partition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploytask',
            options={'permissions': (('scan_deploytask', 'Can scan deploytask info'), ('examine_deploytask', 'Can examine deploytask'), ('backspace_deploytask', 'Can backspace deploytask'), ('upgrade_deploytask', 'Can upgrade 升级任务'), ('upgrade_partition', 'Can upgrade partition 升级任务')), 'verbose_name': '升级任务', 'verbose_name_plural': '升级任务'},
        ),
    ]
