# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0021_auto_20180929_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='upgrade_partition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='是否需要先升级部分节点'),
        ),
        migrations.AlterField(
            model_name='deploytask',
            name='is_upgrade_partition',
            field=models.CharField(default='no', max_length=255, verbose_name='是否升级部分节点'),
        ),
    ]
