# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0023_auto_20180929_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='is_upgrade_continue',
            field=models.CharField(default='no', max_length=255, verbose_name='是否继续升级'),
        ),
    ]
