# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0024_deploytask_is_upgrade_continue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlExecute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdsinstance', models.CharField(blank=True, max_length=255, null=True, verbose_name='rds实例名称')),
                ('rdsschema', models.CharField(blank=True, max_length=255, null=True, verbose_name='rds数据库名称')),
                ('sqlfile', models.CharField(blank=True, max_length=255, null=True, verbose_name='sql文件名称')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sql执行',
                'verbose_name_plural': 'sql执行',
                'permissions': (('uploade_sql', 'Can upload SQL文件'),),
            },
        ),
    ]
