# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-08 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0026_auto_20181008_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlexecute',
            name='upload_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传文件用户'),
        ),
    ]
