# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-09 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0027_sqlexecute_upload_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlexecute',
            options={'permissions': (('scan_sql', 'Can scan SQL文件'), ('upload_sql', 'Can upload SQL文件')), 'verbose_name': 'sql执行', 'verbose_name_plural': 'sql执行'},
        ),
    ]
