# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-27 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_rdsinstance_rdsschema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdsschema',
            name='rdsinstanc',
        ),
        migrations.DeleteModel(
            name='RdsInstance',
        ),
        migrations.DeleteModel(
            name='RdsSchema',
        ),
    ]
