# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-27 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_rdsinstance_rdsschema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdsschema',
            old_name='rdsinstanc',
            new_name='rdsinstane',
        ),
    ]
