# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20180827_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255, verbose_name='java进程名称')),
                ('process_cmd', models.CharField(blank=True, max_length=255, null=True, verbose_name='java进行启动参数')),
                ('process_port', models.CharField(max_length=255, verbose_name='java进程启动端口')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='所属主机')),
            ],
            options={
                'verbose_name': '进程',
                'verbose_name_plural': '进程',
                'permissions': (('scan_process', 'Can scan 进程'),),
            },
        ),
    ]
