# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcsHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255, verbose_name='ECS实例ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机名')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机描述')),
                ('local_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='内网IP')),
                ('internet_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='公网IP')),
                ('elastic_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='弹性IP')),
                ('cpu_nums', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU配置')),
                ('memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='内存配置')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='带宽配置')),
                ('minion_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='saltstack minion_id')),
            ],
            options={
                'verbose_name': 'ECS主机',
                'verbose_name_plural': 'ECS主机',
                'permissions': (('scan_ecshost', 'Can scan ECS主机'),),
            },
        ),
    ]
