# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20180830_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecshost',
            name='network_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='网络类型'),
        ),
    ]
