# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_ecshost_network_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecshost',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='主机名'),
        ),
    ]
