# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-31 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_auto_20180830_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='process_cmd',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_port',
        ),
        migrations.AddField(
            model_name='process',
            name='process_hostpath',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='进程HOME目录'),
        ),
        migrations.AddField(
            model_name='process',
            name='projectmodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ProjectModule', verbose_name='所属模块'),
        ),
    ]
