# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-11 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_auto_20180910_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'permissions': (('scan_cluster', 'Can scan cluster info'), ('resource_manage', 'Can manage 资源'), ('project_manage', 'Can manage 项目'), ('ldap_add', 'Can add LDAP用户'), ('project_upgrade', 'Can upgrade 项目')), 'verbose_name': '集群', 'verbose_name_plural': '集群'},
        ),
    ]
