# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-14 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20180911_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='ecshost',
        ),
        migrations.RemoveField(
            model_name='process',
            name='projectmodule',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
