# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20180914_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_name', models.CharField(max_length=255, verbose_name='state名称')),
                ('fun_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='功能描述')),
                ('state_dir', models.CharField(blank=True, max_length=255, null=True, verbose_name='state目录')),
            ],
            options={
                'verbose_name': 'saltstack state',
                'verbose_name_plural': 'saltstack state',
            },
        ),
    ]
