# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_saltstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255, verbose_name='java进程名称')),
                ('process_homepath', models.CharField(blank=True, max_length=255, null=True, verbose_name='进程HOME目录')),
                ('ecshost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.EcsHost', verbose_name='所属主机')),
                ('projectmodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ProjectModule', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '进程',
                'verbose_name_plural': '进程',
                'permissions': (('scan_process', 'Can scan 进程'),),
            },
        ),
    ]
