# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-10 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='进程ID'),
        ),
        migrations.AddField(
            model_name='process',
            name='process_log',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='进程启动日志'),
        ),
        migrations.AddField(
            model_name='process',
            name='process_port',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='进程端口'),
        ),
    ]
